[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "rayuela"
version = "0.1.0"

[tool.setuptools]
packages = ["app"]

[tool.setuptools.package-dir]
"app" = "app"